# This file was generated by Project Manager.
{ allow-import-from-derivation = true; auto-retry = true; build-logs = true; deploy = { }; doNotBuild = [ "devShells.x86_64-linux.lax-checks" ]; fail-fast = false; impure = false; test = { }; }
